// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aquarium.Domain.Entities;

public partial class Category
{
    public Guid Id { get; set; }

    public string Name { get; set; }
    public string Slug { get; set; } = string.Empty;

    public string? Description { get; set; }

    public Guid? StoreId { get; set; }

    public Guid? ParentId { get; set; }

    public virtual ICollection<Category> InverseParent { get; set; } = new List<Category>();

    public virtual Category Parent { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual Store Store { get; set; }
}