// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aquarium.Domain.Entities;

public partial class Conversation
{
    public Guid Id { get; set; }

    public Guid StoreId { get; set; }

    public Guid CustomerId { get; set; }

    public string LastMessage { get; set; }

    public DateTime? LastMessageAt { get; set; }

    public virtual User Customer { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual Store Store { get; set; }
}