// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aquarium.Domain.Entities;

public partial class FishInstance
{
    public Guid Id { get; set; }

    public Guid ProductId { get; set; }

    public decimal Price { get; set; }

    public string Size { get; set; }

    public string Color { get; set; }

    public string Features { get; set; }

    public string Gender { get; set; }

    public string VideoUrl { get; set; }

    public string VideoPublicId { get; set; }

    public string Status { get; set; } = "Available";

    public DateTime CreatedAt { get; set; }

    public DateTime? SoldAt { get; set; }

    public DateTime? ReservedUntil { get; set; }

    public virtual Product Product { get; set; }

    public virtual ICollection<FishInstanceMedia> FishInstanceMedia { get; set; } = new List<FishInstanceMedia>();
}
