// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aquarium.Domain.Entities;

public partial class FishInstanceMedia
{
    public Guid Id { get; set; }

    public Guid FishInstanceId { get; set; }

    public string MediaUrl { get; set; }

    public string PublicId { get; set; }

    public string MediaType { get; set; }

    public bool IsPrimary { get; set; } = false;

    public int DisplayOrder { get; set; } = 0;

    public DateTime CreatedAt { get; set; }

    public virtual FishInstance FishInstance { get; set; }
}
