// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Aquarium.Domain.Entities;

public partial class Inventory
{
    public Guid Id { get; set; }

    public Guid ProductId { get; set; }

    public int Quantity { get; set; }

    public int QuantityReserved { get; set; }

    public int AvailableStock => Quantity - QuantityReserved;

    public DateTime LastUpdated { get; set; }

    [Timestamp]
    public byte[] RowVersion { get; set; }

    public virtual Product Product { get; set; }

    public virtual ICollection<InventoryHistory> Histories { get; set; } = new List<InventoryHistory>();
}