// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aquarium.Domain.Entities;

public partial class Message
{
    public Guid Id { get; set; }

    public Guid ConversationId { get; set; }

    public Guid SenderId { get; set; }

    public string Content { get; set; }

    public bool? IsRead { get; set; }

    public string Type { get; set; } = "Text"; //Type (Text, Image, ProductLink...)

    public DateTime? CreatedAt { get; set; } = DateTime.UtcNow;

    public virtual Conversation Conversation { get; set; }
}