// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aquarium.Domain.Entities;

public partial class Order
{
    public Guid Id { get; set; }

    public Guid StoreId { get; set; }

    public Guid CustomerId { get; set; }

    public string Status { get; set; }

    public decimal TotalAmount { get; set; }

    public string ShippingAddress { get; set; }

    public DateTime CreatedAt { get; set; }

    public string? Note { get; set; }

    public string PaymentStatus { get; set; } = "Unpaid";

    public virtual User Customer { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual Store Store { get; set; }
}