// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Aquarium.Domain.Constants;

namespace Aquarium.Domain.Entities;

public partial class Order
{
    public Guid Id { get; set; }

    public Guid StoreId { get; set; }

    public Guid CustomerId { get; set; }

    public string Status { get; set; } = OrderStatus.Pending;

    public decimal TotalAmount { get; set; }

    public string ShippingAddress { get; set; }

    public DateTime CreatedAt { get; set; }

    public string? Note { get; set; }

    public string PaymentStatus { get; set; } = PaymentsStatus.Unpaid;

    public string? PaymentMethod { get; set; } // e.g., "COD", "VNPay", "Wallet"

    public string? TransactionId { get; set; } // ID from Payment Gateway

    public Guid? IdempotencyKey { get; set; }

    public DateTime? PaidAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public virtual User Customer { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual Store Store { get; set; }
}