// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aquarium.Domain.Entities;

public partial class OrderItem
{
    public Guid Id { get; set; }

    public Guid OrderId { get; set; }

    public Guid ProductId { get; set; }

    public Guid? FishInstanceId { get; set; }

    public int Quantity { get; set; }

    // Snapshot Data (The value is fixed at the time of purchase.)
    public string ProductName { get; set; } = string.Empty;
    public decimal PriceAtPurchase { get; set; }
    public string? ProductImageUrl { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

    public virtual FishInstance FishInstance { get; set; }
}