// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aquarium.Domain.Entities;

public partial class PostMedia
{
    public Guid Id { get; set; }

    public Guid PostId { get; set; }

    public string MediaUrl { get; set; }

    public string MediaType { get; set; }

    public virtual StorePost Post { get; set; }
}