// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aquarium.Infrastructure.Persistence;

public partial class ProductMedia
{
    public Guid Id { get; set; }

    public Guid ProductId { get; set; }

    public string MediaUrl { get; set; }

    public string MediaType { get; set; }

    public bool? IsPrimary { get; set; }

    public virtual Product Product { get; set; }
}