// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aquarium.Domain.Entities;

public partial class Product
{
    public Guid Id { get; set; }

    public Guid StoreId { get; set; }

    public Guid CategoryId { get; set; }

    public string Name { get; set; }
    public string Slug { get; set; } = string.Empty;

    public string Type { get; set; }

    public decimal BasePrice { get; set; }

    public string Status { get; set; } = "Pending"; // Default to Pending

    public string? RejectionReason { get; set; } // Optional reason for rejection

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public double AverageRating { get; set; } = 0;

    public int TotalReviews { get; set; } = 0;

    public virtual Category Category { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<ProductMedia> ProductMedia { get; set; } = new List<ProductMedia>();

    public virtual ICollection<ProductReview> ProductReviews { get; set; } = new List<ProductReview>();

    public virtual ICollection<FishInstance> FishInstances { get; set; } = new List<FishInstance>();

    public virtual Store Store { get; set; }

    public virtual ICollection<ProductAttribute> Attributes { get; set; } = new List<ProductAttribute>();
}