// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aquarium.Domain.Entities;

public partial class StoreReview
{
    public Guid Id { get; set; }

    public Guid StoreId { get; set; }

    public Guid UserId { get; set; }

    public Guid OrderId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public string Status { get; set; } = "Active";

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Store Store { get; set; }

    public virtual User User { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<StoreReviewMedia> Media { get; set; } = new List<StoreReviewMedia>();
}
