// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aquarium.Domain.Entities;

public partial class Store
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Slug { get; set; }

    public string Address { get; set; }

    public string DeliveryArea { get; set; }

    public string Status { get; set; }
    public string? RejetionReason { get; set; }

    public string? LogoUrl { get; set; }

    public string? LogoPublicId { get; set; }

    public string? CoverUrl { get; set; }

    public string? CoverPublicId { get; set; }

    public string VideoIntroUrl { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

    public virtual ICollection<Conversation> Conversations { get; set; } = new List<Conversation>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<StorePost> StorePosts { get; set; } = new List<StorePost>();

    public virtual ICollection<StoreReview> StoreReviews { get; set; } = new List<StoreReview>();

    public virtual ICollection<StoreUser> StoreUsers { get; set; } = new List<StoreUser>();
}