// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aquarium.Domain.Entities;

public partial class StorePost
{
    public Guid Id { get; set; }

    public Guid StoreId { get; set; }

    public string Content { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<PostMedia> PostMedia { get; set; } = new List<PostMedia>();

    public virtual Store Store { get; set; }
}