// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aquarium.Infrastructure.Persistence;

public partial class StoreUser
{
    public Guid Id { get; set; }

    public Guid StoreId { get; set; }

    public Guid UserId { get; set; }

    public string Role { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Store Store { get; set; }

    public virtual User User { get; set; }
}